### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by matanox** [dfederschmidt/fasttext-server#7]
Just wondering what kind of prediction performance and throughput can one get with this python/flask implementation.... have any numbers from a load test?

**Comment by dfederschmidt** [comment]
Hi! At the moment I would not expect the performance to be very good since it's just using the web server that ships with flask [which is not suitable for production](http://flask.pocoo.org/docs/0.12/deploying/). But once I'm actually looking at performance I might have a [locust](https://github.com/locustio/locust) test suite to evaluate performance of different implementations. But for now I'm still working on a sensible way to package / document. But be assured that I'll look into getting performance eventually.

**Comment by matanox** [comment]
How do you even get concurrent serving with python? are there any concurrent python servers libraries?

**Comment by messense** [comment]
Hi @matanster , you can try my Rust fastText serving implementation: https://github.com/messense/fasttext-serving

**Comment by matanox** [comment]
Just curious, why rust? is it just your staple programming language?

**Comment by messense** [comment]
I chose Rust because it interface well with C and making a performant REST API server is really easy in Rust than in C/C++.
